pkg/unpackaged/unpackaged/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pkg/unpackaged/unpackaged/objects/Book_Order__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Book Orders</relationshipLabel>
        <relationshipName>BookOrders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Book Order</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>Order Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Book Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pkg/unpackaged/unpackaged/classes/PriceCalculationTest.cls
@isTest
public class PriceCalculationTest {

    @isTest
    public static void calculatePriceTest()
    {
        Book__c book = new Book__c();
        book.Name = '2 States';
        book.Quantity__c = 15;
        book.Price__c = 200;
        insert book;

        Book_Order__c bookOrder = new Book_Order__c();
        List<Book__c> Books = [select id from Book__c where Name='2 States'];
        for(Book__c insertedBook : Books){
            bookOrder.Book__c = insertedBook.id;
        }
        
        insert bookOrder;

        List<Book_Order__c> insertedOrders = [select Total_Price__c from Book_Order__c];
        for(Book_Order__c order : insertedOrders){
            System.assertEquals(300,order.Total_Price__c);
        }
    }
}